### ISSUE TITLE
No profile picture and a translation issue

### ISSUE THREAD

**Issue by L-dong** [mlthelama/DialogueMoreNPCInfo#7]
Hi, i really like this mod .But i got some problems:
1. i have installed IconsForDMNI and other things needed did not make any changes,but i can't see the picture.![ScreenShot14](https://user-images.githubusercontent.com/26449573/188294477-b737b79c-4512-4693-939e-482c7138709c.png)
2. Maybe it's because of non-English characters that the picture can't be found.
3. And another question is that i try to translate the mod  only for myself ,but when i translated the DialogueMoreNPCInfo_english.txt to my native language ,I still get an incomplete translation.
![ScreenShot23](https://user-images.githubusercontent.com/26449573/188295110-af68a7dc-43e6-40ce-a63c-bb0c363d650f.png)
You can see some $ characters.
Here is the log text:
[DialogueMoreNPCInfo.log](https://github.com/mlthelama/DialogueMoreNPCInfo/files/9483739/DialogueMoreNPCInfo.log)

**Comment by mlthelama** [comment]
thanks for the info.

1) seems to have to do with the language, I might have to find another way to get the value for it, have to look around what skse 
2) yes, similar to 1) if i can find a better way to map it, i can do that
3) ok, i think i take most of the values from the language file all with $ something do, i will take a look at it, maybe scaleform plus plus loads a "DialogueMoreNPCInfo_yourlanguage.txt" 

but i will try to make the code inside the plugin more language independent then the images should be found

**Comment by mlthelama** [comment]
Inside the Code I will use the FormIDs and then always set the english names, the Translation files will handle the Rest.

**Comment by mlthelama** [comment]
added to release 1.0.7 here and on nexus
